# Generated by Django 5.2 on 2025-07-29 19:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Gender', models.CharField(blank=True, choices=[('', '--Select Gender--'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10, null=True, verbose_name='Gender')),
                ('DOB', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Blood_Group', models.CharField(blank=True, choices=[('', '--Select Blood Group--'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=5, null=True, verbose_name='Blood Group')),
                ('Nationality', models.CharField(default='Indian', max_length=20)),
                ('Category', models.CharField(choices=[('', '--Select Category--'), ('SC', 'SC'), ('ST', 'ST'), ('NT', 'NT'), ('OBC', 'OBC'), ('General', 'General')], default='', max_length=10, verbose_name='Category')),
                ('Religion', models.CharField(max_length=20)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Father_Name', models.CharField(max_length=80)),
                ('Father_Occupation', models.CharField()),
                ('Mother_Name', models.CharField(max_length=80)),
                ('Mother_Occupation', models.CharField()),
                ('Parents_Address', models.TextField()),
                ('student_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('Roll_Number', models.IntegerField(blank=True, null=True)),
                ('Marks', models.FloatField(blank=True, null=True)),
                ('Department', models.CharField(max_length=20)),
                ('Assigned_Teacher', models.CharField(max_length=50)),
                ('Total_Fees', models.IntegerField(blank=True, null=True)),
                ('Paid_Fees', models.IntegerField(blank=True, null=True)),
                ('Due_Fees', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
