# Generated by Django 5.2 on 2025-07-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
